#
# Copyright (c) 2018-2025, lengleng All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice,
#  this list of conditions and the following disclaimer.
#  Redistributions in binary form must reproduce the above copyright
#  notice, this list of conditions and the following disclaimer in the
#  documentation and/or other materials provided with the distribution.
#  Neither the name of the pig4cloud.com developer nor the names of its
#  contributors may be used to endorse or promote products derived from
#  this software without specific prior written permission.
#  Author: lengleng (wangiegie@gmail.com)
#

server:
  port: 5003

spring:
  application:
    name: pig-report
  profiles:
    active: @profiles.active@
  config:
    import:
      - optional:nacos:${spring.application.name}.yml?refresh=true
      - optional:nacos:application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml

# JimuReport 配置
jeecg:
  jmreport:
    # 数据模式：生产环境建议改为 true
    saas-mode: false
    # 是否启用报表设计器
    open: true